"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiSend } from "../lib/api";
export function ImageManager({ product }: { product: any }) { const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function upload(formData:FormData){ setBusy(true); setError(""); try{ await apiSend(`/admin/products/${product.id}/images`,"POST",formData); router.refresh(); }catch(e:any){setError(e.message)} finally{setBusy(false)} }
  async function del(id:string){ if(!confirm("Фото будет удалено из товара, базы данных и файлового хранилища. Продолжить?")) return; await apiSend(`/admin/products/${product.id}/images/${id}`,"DELETE"); router.refresh(); }
  async function main(id:string){ await apiSend(`/admin/products/${product.id}/images/${id}/main`,"PATCH"); router.refresh(); }
  return <section className="card" style={{padding:24, display:"grid", gap:16}}><h2>Фотографии</h2><form action={upload} style={{display:"grid", gap:12}}><input className="input" type="file" name="file" accept="image/jpeg,image/png,image/webp" required /><input className="input" name="alt" placeholder="Alt text" /><label><input type="checkbox" name="isMain" /> Сделать главным</label><button className="btn" disabled={busy}>{busy?"Загрузка...":"Загрузить фото"}</button>{error && <p style={{color:"#DC2626"}}>{error}</p>}</form><div style={{display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))", gap:14}}>{product.images?.map((img:any)=><div className="card" key={img.id} style={{padding:10}}><div style={{aspectRatio:"1", background:"#E5E7EB", borderRadius:12, overflow:"hidden"}}>{img.thumbUrl && <img src={img.thumbUrl} style={{width:"100%", height:"100%", objectFit:"cover"}} />}</div><p>{img.isMain?"Главное":"Фото"}</p><button className="btn btn-muted" type="button" onClick={()=>main(img.id)}>Главное</button> <button className="btn btn-danger" type="button" onClick={()=>del(img.id)}>Удалить</button></div>)}</div></section> }
