events {}

http {
  client_max_body_size 12m;

  upstream public_frontend { server public-frontend:3000; }
  upstream admin_frontend { server admin-frontend:3001; }
  upstream api_backend { server api:4000; }

  server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/ {
      proxy_pass http://api_backend/api/;
    }

    location /media/ {
      proxy_pass http://api_backend/api/media/;
    }

    location /admin/_next/ {
      proxy_pass http://admin_frontend/admin/_next/;
    }

    location /admin/ {
      proxy_pass http://admin_frontend/admin/;
    }

    location = /admin {
      return 301 /admin/;
    }

    location / {
      proxy_pass http://public_frontend;
    }
  }
}
